### ISSUE TITLE
Step1: where is the script for making patches

### ISSUE THREAD

**Issue by ryupath** [xi11/AIgrading#1]
There is no such file "img_patch_768.py" in a traning_patch directory.
Instead, there is "img2patch.py". 
I tried "img2patch.py", but it did not work. FileNotFoundError appeared. It seems that file names of .mat files are the problem.

**Comment by xi11** [comment]
Hi,
Thanks for reporting the issues!
1. We have updated README.md to reflect the right script, `img2patch.py`.
2. We have tested `img2patch.py` in our side, it was running successfully. 

- Please make sure your input args are correct, one is the path to image, i.e., /xxx/trainset/image, one is the path to mask, i.e., /xxx/trainset/mask, the other one is the path to the saved patches.
- It might be due to the disparity between different OS regarding the following line. If you are running under Windows, please consider replacing `'/'` with `'\\'`; We've also updated with `os.path.basename` to accommodate, which has passed our testing as well.
`data_file_name = data_file.split('/')[-1]  #split path and get the last one, which is the file name; '/' for running under linux, '\\' for running under win`

**Comment by xi11** [comment]
> There is no such file "img_patch_768.py" in a traning_patch directory. Instead, there is "img2patch.py". I tried "img2patch.py", but it did not work. FileNotFoundError appeared. It seems that file names of .mat files are the problem.

Hi,
Thanks for reporting the issues!

1. We have updated README.md to reflect the right script, `img2patch.py`.
2. We have tested `img2patch.py` in our side, it was running successfully.
- Please make sure your input args are correct, one is the path to image, i.e., /xxx/trainset/image, one is the path to mask, i.e., /xxx/trainset/mask, the other one is the path to the saved patches.
- It might be due to the disparity between different OS regarding the following line. If you are running under Windows, please consider replacing `'/'` with `'\\'`; We've also updated with `os.path.basename` to accommodate, which has passed our testing as well.
`data_file_name = data_file.split('/')[-1]  #split path and get the last one, which is the file name; '/' for running under linux, '\\' for running under win`
